### ISSUE TITLE
error running client

### ISSUE THREAD

**Issue by aalshaikh** [keyCat/chatback#1]
Hi, i am trying to run the application but when i hit 0.0.0.0:3000 to get the client it's give me error:
404 Error: Cannot GET /

**Comment by keyCat** [comment]
@aalshaikh

Unfortunately, front-end building is not made automatic, so you will need to manually run appropriate Gulp tasks:

`$ gulp serve` - for development
`$ gulp dist` - for final builds

Also, you may take a look at the `server/middleware.*.js` configuration files where you can change the location from which static files are served by changing `loopback#static` variable.
